"""Shared vocabulary for every ADRL package. Primary: ADRL-FND-001.

Builders import enums, ids, types, ports and errors from here. Nothing in this package
imports from any other ADRL package.
"""

from adrl.core.enums import (
    FAILURE_TYPES_VERSION,
    REQUEST_CLASSES_VERSION,
    AbstainReason,
    DetectorTier,
    EpisodeSignal,
    EvidenceTier,
    FailureClass,
    FailureType,
    GateMode,
    InteractionMode,
    OutcomeState,
    ProjectionState,
    ReleaseReason,
    RequestClass,
    RoutingMode,
    Rung,
    ServedSource,
    SideEffectClass,
    UtilityKind,
    VerificationResult,
    resolve_primary,
)
from adrl.core.errors import (
    AdrlError,
    ConfigError,
    ErrorCode,
    GateFailure,
    LedgerAppendFailure,
    PermittedSetWidened,
    PinnedBlock,
    render_error,
)
from adrl.core.ids import LineageId, RouteId, SessionId, hmac_identity, mint_route_id
from adrl.core.types import (
    HANDOFF_NOTE_DELIMITER,
    HANDOFF_NOTE_SCHEMA_VERSION,
    LOCAL_HOST_ZONE,
    Decision,
    DeploymentInfo,
    DeploymentSet,
    Finding,
    GateVerdict,
    HandoffNote,
    PermittedSet,
    RequestContext,
    ServedIdentity,
    SideEffectRecord,
    Usage,
)

__all__ = [
    "FAILURE_TYPES_VERSION",
    "HANDOFF_NOTE_DELIMITER",
    "HANDOFF_NOTE_SCHEMA_VERSION",
    "LOCAL_HOST_ZONE",
    "REQUEST_CLASSES_VERSION",
    "AbstainReason",
    "AdrlError",
    "ConfigError",
    "Decision",
    "DeploymentInfo",
    "DeploymentSet",
    "DetectorTier",
    "EpisodeSignal",
    "ErrorCode",
    "EvidenceTier",
    "FailureClass",
    "FailureType",
    "Finding",
    "GateFailure",
    "GateMode",
    "GateVerdict",
    "HandoffNote",
    "InteractionMode",
    "LedgerAppendFailure",
    "LineageId",
    "OutcomeState",
    "PermittedSet",
    "PermittedSetWidened",
    "PinnedBlock",
    "ProjectionState",
    "ReleaseReason",
    "RequestClass",
    "RequestContext",
    "RouteId",
    "RoutingMode",
    "Rung",
    "ServedIdentity",
    "ServedSource",
    "SessionId",
    "SideEffectClass",
    "SideEffectRecord",
    "Usage",
    "UtilityKind",
    "VerificationResult",
    "hmac_identity",
    "mint_route_id",
    "render_error",
    "resolve_primary",
]
