"""OpenTelemetry GenAI semantic-convention attribute names. Primary: ADRL-RTG-008."""

GEN_AI_REQUEST_MODEL = "gen_ai.request.model"
GEN_AI_RESPONSE_MODEL = "gen_ai.response.model"
GEN_AI_PROVIDER_NAME = "gen_ai.provider.name"
GEN_AI_USAGE_INPUT_TOKENS = "gen_ai.usage.input_tokens"
GEN_AI_USAGE_OUTPUT_TOKENS = "gen_ai.usage.output_tokens"
GEN_AI_USAGE_CACHE_READ_INPUT_TOKENS = "gen_ai.usage.cache_read_input_tokens"
GEN_AI_USAGE_CACHE_CREATION_INPUT_TOKENS = "gen_ai.usage.cache_creation_input_tokens"
GEN_AI_OPERATION_NAME = "gen_ai.operation.name"
GEN_AI_CONVERSATION_ID = "gen_ai.conversation.id"
GEN_AI_AGENT_ID = "gen_ai.agent.id"

ADRL_ROUTE_ID = "adrl.route_id"
ADRL_LINEAGE = "adrl.lineage"
ADRL_REQUEST_CLASS = "adrl.request_class"
ADRL_DECIDED_RUNG = "adrl.decided_rung"
ADRL_SERVED_RUNG = "adrl.served_rung"
ADRL_SERVED_SOURCE = "adrl.served_source"
ADRL_PINNED = "adrl.pinned"
ADRL_UNSCANNED = "adrl.unscanned"
